services:
  mongodb:
    image: mongo:7.0
    restart: on-failure
    networks: [graylog]
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  datanode:
    image: graylog/graylog-datanode:7.1.5
    hostname: datanode
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: /var/lib/graylog-datanode/node-id
      GRAYLOG_DATANODE_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_DATANODE_MONGODB_URI: mongodb://mongodb:27017/graylog
      GRAYLOG_DATANODE_SKIP_PREFLIGHT_CHECKS: "true"
    ulimits:
      memlock: {hard: -1, soft: -1}
      nofile: {hard: 65536, soft: 65536}
    networks: [graylog]
    volumes:
      - datanode_data:/var/lib/graylog-datanode
    restart: on-failure

  graylog:
    image: graylog/graylog:7.1.5
    hostname: server
    depends_on:
      mongodb: {condition: service_started}
      datanode: {condition: service_started}
    environment:
      GRAYLOG_NODE_ID_FILE: /usr/share/graylog/data/data/node-id
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
      GRAYLOG_MONGODB_URI: mongodb://mongodb:27017/graylog
      GRAYLOG_SKIP_PREFLIGHT_CHECKS: "true"
    ports:
      - 127.0.0.1:9000:9000/tcp
      - 127.0.0.1:1515:1515/udp
    networks: [graylog]
    volumes:
      - graylog_data:/usr/share/graylog/data
      - ../lookups:/usr/share/graylog/data/unifi-gim:ro
    restart: on-failure

networks:
  graylog:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config:
  datanode_data:
  graylog_data:

